DROP TABLE IF EXISTS PROBLEMS;

CREATE TABLE PROBLEMS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE TEXT NOT NULL,
    QUESTION TEXT NOT NULL,
    ANSWER TEXT NOT NULL,
    DIFFICULTY TEXT CHECK(DIFFICULTY IN ('easy', 'medium', 'hard')) NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
